version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
